import { ThemeProvider } from "@/components/providers/ThemeProvider";
import "./globals.css";
import type { Metadata } from "next";
import { Open_Sans } from "next/font/google";
import { cn } from "@/lib/utils";
import { ClerkProvider, UserButton } from "@clerk/nextjs";
import { ToasterProvider } from "@/components/providers/ToastProvider";
import Menu from "@/components/sidebar/Menu";
import Navbar from "@/components/navbar/Navbar";
import { intialProfile } from "@/lib/setInitialProfile";
import { ModalProvider } from "@/components/providers/ModalProvider";
import { getServerSession } from "next-auth";
import SessionProvider from "@/components/providers/SessionProvider";
import LoginModal from "@/components/modals/LoginModal";
import { signOut } from "next-auth/react";
import Auth from "@/components/Auth";

const font = Open_Sans({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const user = await intialProfile();
  const session = await getServerSession();

  return (
    <ClerkProvider>
      <html lang="en" suppressHydrationWarning>
        <body className={cn(font.className, "bg-white dark:bg-slate-900 ")}>
          <SessionProvider session={session}>
            <ThemeProvider
              attribute="class"
              defaultTheme="system"
              enableSystem
              disableTransitionOnChange
            >
              <ModalProvider />
              <ToasterProvider />
              <LoginModal />
              {session ? (
                <>
                  <Navbar user={user} />
                  <Menu />
                  {children}
                </>
              ) : (
                <>
                  <Auth />
                </>
              )}
              
            </ThemeProvider>
          </SessionProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}
