import { ThemeProvider } from '@/components/providers/ThemeProvider'
import './globals.css'
import type { Metadata } from 'next'
import { Open_Sans } from 'next/font/google'
import { cn } from '@/lib/utils'
import { ClerkProvider } from '@clerk/nextjs'
import { ToasterProvider } from '@/components/providers/ToastProvider'
import Menu from '@/components/sidebar/Menu'
import Navbar from '@/components/navbar/Navbar'
import { intialProfile } from '@/lib/setInitialProfile'
import AdminAuthentication from '@/components/admin/AdminAuthentication'

const font = Open_Sans({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
    const user=await intialProfile();
  return (
    <ClerkProvider>
    <html lang="en" suppressHydrationWarning>
      <body 
        className={cn(
          font.className,
          'bg-white dark:bg-slate-900 '
        )}
      >
        <ThemeProvider
          attribute='class'
          defaultTheme='system'
          enableSystem
          disableTransitionOnChange
        >
          <ToasterProvider/>
          <Menu/>
          <Navbar user={user}/>
          {children}
        </ThemeProvider>
      </body>
    </html>
    </ClerkProvider>
  )
}
